# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'Tools.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QDesktopWidget


class Ui_mainWindow(object):
    def __init__(self):
        # 获取系统分辨率
        app = QApplication(sys.argv)
        screen = QDesktopWidget().screenGeometry()
        screen_width = screen.width()
        screen_height = screen.height()
        # 获取比例
        self.with_scale = screen_width / 1920
        self.height_scale = screen_height / 1080

    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 500)
        mainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 700, 40))
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 100, 120, 40))
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 100, 120, 40))
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(580, 100, 120, 40))
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(410, 100, 120, 40))
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(240, 170, 120, 40))
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(410, 170, 120, 40))
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(50, 170, 120, 40))
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(580, 170, 120, 40))
        mainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(mainWindow)

    def generate_control_xy(self):
        start_x = 50
        start_y = 100
        while True:
            yield (start_x * self.with_scale, start_y * self.height_scale)
            if start_x + 190 >= 800:
                start_y += 70
                start_x = 50
            else:
                start_x += 190
        #     return (start_x * self.with_scale, start_y * self.height_scale)
        # #

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Tools"))
        self.label.setText(_translate("mainWindow", "TextLabel"))
        self.pushButton.setText(_translate("mainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("mainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("mainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("mainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("mainWindow", "PushButton"))
        self.pushButton_6.setText(_translate("mainWindow", "PushButton"))
        self.pushButton_7.setText(_translate("mainWindow", "PushButton"))
        self.pushButton_8.setText(_translate("mainWindow", "PushButton"))


if __name__ == '__main__':
    a = Ui_mainWindow().generate_control_xy()
    for i in range(8):
        print(next(a))
